### ISSUE TITLE
Glue Connection properties is not permitted for use due to plaintext credentials

### ISSUE THREAD

**Issue by psg9999** [stelligent/config-lint#100]

**Comment by kmonihen** [comment]
connection_properties is required https://www.terraform.io/docs/providers/aws/r/glue_connection.html#connection_properties

I'm writing the rule to fail if PASSWORD is present in the connection_properties.

`  - id: GLUE_CONNECTION_PROPERTIES
    message: Glue connection properties cannot specify plaintext passwords
    resource: aws_glue_connection
    severity: FAILURE
    assertions:
      - key: connection_properties[].PASSWORD | [0]
        op: absent
    tags:
      - glue`
