### ISSUE TITLE
Create Warning when custom kms_key isn't used alongside encryption

### ISSUE THREAD

**Issue by phelewski** [stelligent/config-lint#142]
There are several resources that already have rules in place to ensure they are using encryption. These can be enabled without a specific kms_key, as without one defined the default one from the aws service will be used. It would be nice to see a warning for a resource that already has encryption enabled, but doesn't specify a specific kms_key.

**Comment by kmonihen** [comment]
Looking at the following rules to see where we can add warnings for missing KMS keys.

CODEBUILD_PROJECT_ENCRYPTION
KINESIS_STREAM_ENCRYPTION
TRANSCODER_REQUIRE_ENCRYPTION
S3_BUCKET_OBJECT_ENCRYPTION
S3_BUCKET_ENCRYPTION
DOCUMENTDB_STORAGE_ENCRYPTION
NEPTUNE_DB_ENCRYPTION
CODEPIPELINE_ENCRYPTION
SQS_QUEUE_ENCRYPTION
REDSHIFT_CLUSTER_ENCRYPTION
KINESIS_FIREHOSE_DELIVERY_STREAM_ENCRYPTION
ELASTICACHE_ENCRYPTION_REST
ELASTICACHE_ENCRYPTION_TRANSIT
RDS_CLUSTER_ENCYPTION
ELASTICSEARCH_NODE_TO_NODE_ENCRYPTION
EBS_BLOCK_DEVICE_ENCRYPTED

**Comment by kmonihen** [comment]
Adding:
RDS_CLUSTER_ENCYPTION_KMS
EBS_BLOCK_DEVICE_ENCRYPTED_KMS
ELASTICACHE_ENCRYPTION_REST_KMS
REDSHIFT_CLUSTER_ENCRYPTION_KMS
S3_BUCKET_KMS
DOCUMENTDB_STORAGE_KMS
NEPTUNE_DB_KMS

Already checks for KMS key:
KINESIS_FIREHOSE_DELIVERY_STREAM_ENCRYPTION
SQS_QUEUE_ENCRYPTION
CODEBUILD_PROJECT_ENCRYPTION
KINESIS_STREAM_KMS
TRANSCODER_REQUIRE_ENCRYPTION
S3_BUCKET_OBJECT_ENCRYPTION
CODEPIPELINE_ENCRYPTION

Not applicable:
ELASTICSEARCH_NODE_TO_NODE_ENCRYPTION
ELASTICACHE_ENCRYPTION_TRANSIT
