### ISSUE TITLE
trying to check kubernetes yamls

### ISSUE THREAD

**Issue by namloc2001** [stelligent/config-lint#150]
Hi, I'm running:
```
docker run -v $(pwd):/foobar stelligent/config-lint -rules example-files/rules/kubernetes.yml /foobar/configmap.yaml`
```
but I get this response:
```
Failed to load rules: open example-files/rules/kubernetes.yml: no such file or directory
```

When I run:
```
docker run -v $(pwd):/foobar stelligent/config-lint -rules
```
It gives:
```
flag needs an argument: -rules
Usage of /config-lint:
  -debug
    	Debug logging
  -exclude value
    	Filename pattern
```
(etc., etc..) So it appears to run ok, but can't find the rules. As I can't look inside the container (it exits straightaway) I'm struggling to debug. I just want to check kubernetes files, nothing else.

Thanks,

Matt

**Comment by phelewski** [comment]
@namloc2001 You will need to put the example Kubernetes rules into your local path and referencing to it accordingly, or you can have your own set of rules that you want to validate against. 

For example:
``` bash
docker run -v $(pwd):/foobar stelligent/config-lint -rules /foobar/path/to/my/rules/kubernetes.yml /foobar/path/to/my/configs/configmap.yaml
```

If you don't have your own set of custom rules that you want to run against your Kubernetes file then feel free to copy or download the example set that is listed here within the project.

At this time there isn't a default rule set for Kubernetes, but I will go ahead and create a new Issue for this as a new feature request.

**Comment by phelewski** [comment]
Issue #151 has been created to handle this new feature request.

**Comment by namloc2001** [comment]
Thanks, I've created a pull request to apply some changes to the README.md as this had me stumped for a while.
