### ISSUE TITLE
Support terraform variable maps

### ISSUE THREAD

**Issue by protoz** [stelligent/config-lint#18]
Some of our repositories are trying to stay as DRY as possible in their code and heavily using built in Terraform features such as maps for defining tags.

**variables.tf**
`variable "common_tags" {
  description = "Common resource tags."
  type        = "map"`

**module.tf** <-- Fails linting
` tags = ${var.common_tags}`

Where the variables are set and rendered on apply per environment:

**main.tf**
`  common_tags = "${map(
    "App", "App Name",
    "Product", "Product",
    "Team", "My Team",
  )}"`

Having config-lint being able to render out the map would be fantastic as the alternative is to modify the rules to look for the required tags or $(var.common_tags) which feels like a band-aid.

**Comment by kmonihen** [comment]
This should be fixed now via https://github.com/stelligent/config-lint/pull/164
