### ISSUE TITLE
create installation method for windows

### ISSUE THREAD

**Issue by kidbrax** [stelligent/config-lint#191]
We can easily enough download and get the executable working with the full path to the exe but can't get it working without specifying full path. I am researching more, but this Powershell snippet gets the exe on the machine in what **should** be in the $PATH.

```
$Version = '1.0.0'
$Url = "https://github.com/stelligent/config-lint/releases/download/v1.0.0/config-lint_$($Version)_Windows_x86_64.zip"
$TempFile = New-TemporaryFile | Rename-Item -NewName { $_ -replace 'tmp$', 'zip' } -PassThru
Write-Output("temp file: $TempFile")
Invoke-WebRequest -OutFile $TempFile $Url
$InstallDir = New-Item -Path "$HOME/AppData/Local/Programs/" -Name "Stelligent" -ItemType Directory -Force
$TempFile | Expand-Archive -DestinationPath $InstallDir -Force
$TempFile | Remove-Item
```

**Comment by kmonihen** [comment]
Closing for now. We can reopen this if there is a need to have a Windows installer beyond adding the executable to the path.
