### ISSUE TITLE
error in homebrew-tap/Formula/mu-cli.rb to prevent installation with homebrew on MacOS

### ISSUE THREAD

**Issue by sherryxcheng** [stelligent/config-lint#214]
When executed installation command on MacOS 'brew tap stelligent/tap', failed with error:

_

> Updating Homebrew...
> ==> Auto-updated Homebrew!
> Updated 2 taps (homebrew/core and aws/tap).
> ==> New Formulae
> alsa-lib                 cli11                    httpx                    libirecovery             numcpp                   podman                   snap                     usb.ids
> borgbackup               croc                     infracost                libseccomp               openfst                  prometheus-cpp           sponge                   volk
> castget                  dbdeployer               inja                     localstack               ormolu                   protoc-gen-gogo          sqlite-utils             vtk@8.2
> cdktf                    diskonaut                ioctl                    mariadb@10.4             parallel-hashmap         protoc-gen-gogofaster    staticcheck              wownero
> clang-format@8           go@1.14                  ladspa-sdk               mhonarc                  periscope                sleef                    terrascan
> ==> Updated Formulae
> Updated 2663 formulae.
> ==> Deleted Formulae
> wpscan
> 
> ==> Tapping stelligent/tap
> Cloning into '/usr/local/Homebrew/Library/Taps/stelligent/homebrew-tap'...
> remote: Enumerating objects: 40, done.
> remote: Counting objects: 100% (40/40), done.
> remote: Compressing objects: 100% (24/24), done.
> remote: Total 1348 (delta 17), reused 33 (delta 16), pack-reused 1308
> Receiving objects: 100% (1348/1348), 176.99 KiB | 35.00 KiB/s, done.
> Resolving deltas: 100% (409/409), done.
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/stelligent/homebrew-tap/Formula/mu-cli.rb
> mu-cli: Calling 'devel' blocks in formulae is disabled! Use 'head' blocks or @-versioned formulae instead.
> Please report this issue to the stelligent/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
>   /usr/local/Homebrew/Library/Taps/stelligent/homebrew-tap/Formula/mu-cli.rb:13
> 
> Error: Cannot tap stelligent/tap: invalid syntax in tap!

_

**Comment by itewk** [comment]
anyone find a soluiton to this?

**Comment by itewk** [comment]
created https://github.com/stelligent/homebrew-tap/pull/5 which worked for me

**Comment by arothian** [comment]
The issue with the brew formula should not be resolved. Let us know if you still are seeing issues with the brew install.

**Comment by sherryxcheng** [comment]
Confirm it works for me now as well, appreciate the quick fix!!
