### ISSUE TITLE
Review Terraform 0.12 / hcl 2 

### ISSUE THREAD

**Issue by twellspring** [stelligent/config-lint#29]
Per https://www.hashicorp.com/blog/announcing-terraform-0-12 Terraform v 0.12 has been released and is using HCL 2.  

We need to review the changes and create a set of issues for supporting Terraform 0.12.

**Comment by phelewski** [comment]
Initial Beta release here with Terraform v0.12 support: [v0.0.40-beta](https://github.com/stelligent/config-lint/releases/tag/v0.0.40-beta)

**Comment by kmonihen** [comment]
Latest release now includes v0.12 support.
