### ISSUE TITLE
Improve development installation instructions

### ISSUE THREAD

**Issue by twellspring** [stelligent/config-lint#30]

**Comment by kmonihen** [comment]
I think we could improve this process by including a development environment. I have been using the VS Code remote containers extension to launch directories in a container for local dev purposes. I'd advocate for using that pattern. The extension uses a plain ol' Dockerfile, so it can be quickly adapted by devs that use other means to spin up environments.

**Comment by twellspring** [comment]
Quick update based on my experiences done on #31 

We can include @kmonihen suggestions under this same issue.

**Comment by kmonihen** [comment]
This is resolved with the use of the VSCode extension or using thestelligent/vscode-remote-config-lint image.

Any other dev documentation improvement can be done in dedicated ticket(s).
