### ISSUE TITLE
Push to DockerHub

### ISSUE THREAD

**Issue by kmonihen** [stelligent/config-lint#34]
We should add a step to the deployment process to push config-lint to the Stelligent DockerHub under https://hub.docker.com/r/stelligent/config-lint.

This is currently not a high priority, but will make config-lint more accessible for quickly adding to deployment pipelines.

**Comment by phelewski** [comment]
This is implemented now with PR #57

**Comment by phelewski** [comment]
This is implemented now with PR #57
