### ISSUE TITLE
Rule top warn on ipProtocol -1

### ISSUE THREAD

**Issue by twellspring** [stelligent/config-lint#37]
See https://github.com/stelligent/cfn_nag/issues/273

Setting IpProtocol: '-1' can produce unexpected results. Per the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule.html#cfn-ec2-security-group-rule-ipprotocol), when -1 is used, ToPort and FromPort are essentially ignored and access is granted on all ports from all protocols.

Terraform documentation shows a similar use of -1
https://www.terraform.io/docs/providers/aws/r/security_group.html

**Comment by kmonihen** [comment]
SG_EGRESS_ALL_PROTOCOLS and SG_INGRESS_ALL_PROTOCOLS cover this.
