### ISSUE TITLE
Fix the build status badge in README.md

### ISSUE THREAD

**Issue by kmonihen** [stelligent/config-lint#48]
Replace the broken CircleCI build status badge with the GitHub Actions build status badge.

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

**Comment by phelewski** [comment]
I've pushed a fix for this here https://github.com/stelligent/config-lint/pull/52/commits/2fa77e5503f4d4c9bec6b3b20483f103aa6eeb6b

Waiting to be merged into master.
